augment: spec_augment

wavs_path: /kaggle/input/pretrainserdataset22k/pretrain_ser_dataset/wavs

train_path: /kaggle/input/pretrainserdataset22k/pretrain_ser_dataset/train.csv
test_path: /kaggle/input/pretrainserdataset22k/pretrain_ser_dataset/test.csv
feature: mfcc

define: &hidden_dim 80
hidden_dim: *hidden_dim

valid_size: 0.1

audio:
  max_duration: 6
  sample_rate: 22050
  max_wav_value: 32768.0
stft:
  filter_length: 1024
  hop_length: 256
  win_length: 1024

mel:
  n_mel_channels: 80
  mel_fmin: 0
  mel_fmax: 8000

label:
  neutral: 0
  angry: 1
  happy: 2
  sad: 3
