define: &sample_rate 22050

mode: train
seed: 42
n_epoch: 100
device: 'cuda'
num_worker: 2
batch_size: 64
random_seed: 42
model_config: configs/models/conformer.yaml
data_config: configs/datas/multilingual.yaml

log_dir: logs
checkpoint_dir: checkpoints
warm_up: None

start_lr: 0.01
end_lr: 0.0001
total_iters: 50

weight_decay: 1e-6
beta1: 0.93
beta2: 0.98

augment: spec_augment
evaluate_per_epoch: 1