define: &sample_rate 22050

mode: train
seed: 42
n_epoch: 100
device: 'cuda'
num_worker: 2
batch_size: 64
random_seed: 42
model_config: configs/models/conformer.yaml
data_config: configs/datas/multilingual.yaml

log_dir: logs
checkpoint_dir: checkpoints
warm_up: None

lr: 0.1
start_factor: 1.0
end_factor: 0.05
total_iters: 20

weight_decay: 1e-6
beta1: 0.93
beta2: 0.98

augment: spec_augment
evaluate_per_epoch: 1